### PR TITLE
Fail if duplicate environment variables are found

### LINKED ISSUE #5: Error/print warning when secret variable occurs more than once
Since we now support custom variables (#3), users can make the mistake of assigning to a variable more than once. We need to either error out or print a warning in this case

### PR DESCRIPTION
**Pull request by futtetennista**
Fixes #5 

In the issue the options mentioned are failing or printing a warning: I leaned towards the former since overriding a variable name is most of the times something done by accident in my experience. But let me know what you folks think about it, if you have a different opinion it won't take much work to change the PR.

The time complexity of `dups` is still quadratic but since that wasn't seen as a performance issue before I didn't use a better one.

### CODE REVIEW

File: app/Main.hs [hunk 1]
```diff
@@ -130,17 +130,29 @@ main = do
   newEnvOrErrors <- Async.mapConcurrently (requestSecret opts) secrets
 
   let
+    checkNoDuplicates e =
+      let keys = map fst (e ++ env)
+      in case dups keys of
+           Left x -> errorWithoutStackTrace $ "Found duplicate variable \"" ++ x ++ "\""
```
Comment (arianvp) [inline app/Main.hs]: Justa driveby comment. @duijf perhaps we cant to switchj away from `errorWithoutStackTrace` and move to `ExceptT/Either` ?  Partial functions are never fun.

Comment (duijf) [reply app/Main.hs]: We can look into that! I do prefer merging this PR first though

Comment (duijf) [reply app/Main.hs]: Right now, we do use `Either` and only run `errorWithoutStackTrace` in `main`. That won't change if we put this logic in `Either`/`ExceptT`, right? (Can you open an issue where you make the case for this if you think this is important?)

File: app/Main.hs [hunk 2]
```diff
@@ -130,17 +130,29 @@ main = do
...
+           _ -> e ++ env
     newEnv = case sequence newEnvOrErrors of
       -- We need to eliminate duplicates in the environment and keep
```
Comment (duijf) [inline app/Main.hs]: Can you update this comment? `nubBy` has been removed

**Comment by futtetennista** [comment]
Thanks for the feedback! I need to solve the conflicts with master before this can be merged, I could either merge this branch or rebase it and then force push it to have a cleaner history: do you folks have any preferences?

**Comment by duijf** [comment]
Thanks for the quick improvements, I'll take a look whenever you think they're ready! 

We prefer rebase + force push :smile:

**Comment by futtetennista** [comment]
@duijf I believe it's now ready for a review 🙂

File: app/Main.hs (hunk 1 above)
Comment (arianvp) [reply app/Main.hs]: The case is that partial functions are always evil :tm: but i'll make a separate issue for it :)

**Comment by futtetennista** [comment]
I agree. :) I read your comments above but since that wasn't the goal of
this PR I preferred to keep it simple and focused.

**Comment by duijf** [comment]
Merged! Thanks a lot for addressing the comments and adding the integration test! :heart:

**Comment by futtetennista** [comment]
Glad I was able to contribute…and have fun in the process ;-)
